package migraterun

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/PhelipeViana/gokit/internal/config"
	"github.com/PhelipeViana/gokit/migration/acao"
)

// GenerateORM rebuilds the application-owned mapping layer from migrations.
// Runtime behaviour never goes into this output: it remains in gokit/orm.
func GenerateORM(root string, state config.ConfigState) (int, error) {
	shapes, err := tableShapes(root, state)
	if err != nil {
		return 0, err
	}
	target := filepath.Join(root, filepath.FromSlash(state.Config.Output.ORM), "fields.gen.go")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return 0, err
	}
	names := make([]string, 0, len(shapes))
	for name := range shapes {
		names = append(names, name)
	}
	sort.Strings(names)
	var out strings.Builder
	out.WriteString("// Code generated by GoKit from migrations. DO NOT EDIT.\npackage orm\n\n")
	out.WriteString("import gokitorm \"github.com/PhelipeViana/gokit/orm\"\n\n")
	for _, name := range names {
		shape := shapes[name]
		entity := exportedORMIdentifier(shape.Table)
		fmt.Fprintf(&out, "var %sField = struct {\n", entity)
		for _, column := range shape.Columns {
			fmt.Fprintf(&out, "\t%s gokitorm.Field\n", exportedORMIdentifier(column.Name))
		}
		out.WriteString("}{\n")
		for _, column := range shape.Columns {
			fmt.Fprintf(&out, "\t%s: gokitorm.Field{Name: %q, Entity: %q, Table: %q, Column: %q, DataType: %q, Nullable: %t, PrimaryKey: %t, AutoIncrement: %t, Unique: %t, Reference: %q},\n", exportedORMIdentifier(column.Name), exportedORMIdentifier(column.Name), shape.Table, shape.Table, column.Name, column.Type, column.Nullable, column.PrimaryKey, column.AutoIncrement, column.Unique, reference(column))
		}
		out.WriteString("}\n\n")
		fmt.Fprintf(&out, "var %sFilter = struct {\n", entity)
		for _, column := range shape.Columns {
			fmt.Fprintf(&out, "\t%s %s\n", exportedORMIdentifier(column.Name), filterType(column.Type))
		}
		out.WriteString("}{\n")
		for _, column := range shape.Columns {
			fmt.Fprintf(&out, "\t%s: %s(%sField.%s),\n", exportedORMIdentifier(column.Name), filterConstructor(column.Type), entity, exportedORMIdentifier(column.Name))
		}
		out.WriteString("}\n\n")
		fmt.Fprintf(&out, "var %sModel = gokitorm.NewModel(gokitorm.EntityFields{Name: %q, Fields: []gokitorm.Field{", entity, shape.Table)
		for i, column := range shape.Columns {
			if i > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "%sField.%s", entity, exportedORMIdentifier(column.Name))
		}
		out.WriteString("}})\n\n")
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return 0, err
	}
	_ = os.Remove(target)
	if err := os.WriteFile(target, formatted, 0o644); err != nil {
		return 0, err
	}
	return len(names), nil
}

func reference(column acao.ColunaDefinicao) string {
	if column.ReferenceTable == "" {
		return ""
	}
	return column.ReferenceTable + "." + column.ReferenceColumn
}

func filterType(kind string) string {
	switch strings.ToLower(kind) {
	case "integer", "int", "decimal":
		return "gokitorm.NumberFilterField"
	case "boolean":
		return "gokitorm.BoolFilterField"
	case "date", "datetime", "timestamp":
		return "gokitorm.DateFilterField"
	default:
		return "gokitorm.StringFilterField"
	}
}
func filterConstructor(kind string) string {
	switch filterType(kind) {
	case "gokitorm.NumberFilterField":
		return "gokitorm.NumberFilter"
	case "gokitorm.BoolFilterField":
		return "gokitorm.BoolFilter"
	case "gokitorm.DateFilterField":
		return "gokitorm.DateFilter"
	default:
		return "gokitorm.StringFilter"
	}
}
func exportedORMIdentifier(value string) string {
	parts := strings.FieldsFunc(strings.ToLower(value), func(r rune) bool { return r == '_' || r == '-' || r == ' ' })
	for i := range parts {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
