package i18n

// Textos da geração de configuração de editor e do guia docs/editores.md.
//
// As TAGS de anotação (TODO, FIXME, NOTE, WARN, HACK, GOKIT) NÃO estão aqui de
// propósito: elas ficam em inglês porque é o que IDE, linter e todo-tree
// reconhecem. O que é multi-vocabulário são os SINÔNIMOS aceitos na varredura
// (TAREFA, CORRIGIR, ATENÇÃO...), agrupados na tag inglesa — quem escreve em
// português continua aparecendo na árvore, sem quebrar ferramenta nenhuma.
func init() {
	Register(Entradas{
		// ── Passo do reload ──
		"rel_step_editors": {
			PT: "Gerar configurações de editor (todo-tree, REST Client, .md)",
			ES: "Generar configuraciones de editor (todo-tree, REST Client, .md)",
			EN: "Generate editor settings (todo-tree, REST Client, .md)",
		},
		"edt_written": {
			PT: "%d arquivo(s) escrito(s)",
			ES: "%d archivo(s) escrito(s)",
			EN: "%d file(s) written",
		},
		"edt_already_current": {
			PT: "Já configurado",
			ES: "Ya configurado",
			EN: "Already configured",
		},
		"edt_settings_unparseable": {
			PT: "%s tem comentários ou sintaxe própria e não foi tocado; as chaves do gokit ficaram em %s para você copiar.",
			ES: "%s tiene comentarios o sintaxis propia y no fue tocado; las claves de gokit quedaron en %s para que las copie.",
			EN: "%s has comments or its own syntax and was left untouched; the gokit keys were written to %s for you to copy.",
		},
		"edt_mkdir_failed": {
			PT: "criar pasta %s: %w",
			ES: "crear la carpeta %s: %w",
			EN: "creating folder %s: %w",
		},
		"edt_write_failed": {
			PT: "escrever %s: %w",
			ES: "escribir %s: %w",
			EN: "writing %s: %w",
		},

		// ── Guia docs/editores.md ──
		"edt_doc_title": {
			PT: "# 🧭 Editores e anotações",
			ES: "# 🧭 Editores y anotaciones",
			EN: "# 🧭 Editors and annotations",
		},
		"edt_doc_intro": {
			PT: "Este guia foi gerado pelo GoKit. Ele descreve as anotações do projeto e como cada editor as apresenta. Nada aqui é obrigatório: as anotações são comentários de código comum e funcionam sem plugin nenhum — o plugin só as organiza em árvore.",
			ES: "Esta guía fue generada por GoKit. Describe las anotaciones del proyecto y cómo las presenta cada editor. Nada aquí es obligatorio: las anotaciones son comentarios de código comunes y funcionan sin ningún plugin — el plugin solo las organiza en árbol.",
			EN: "This guide was generated by GoKit. It describes the project's annotations and how each editor surfaces them. None of it is mandatory: the annotations are ordinary code comments and work with no plugin at all — the plugin only arranges them into a tree.",
		},
		"edt_doc_tags_title": {
			PT: "## Tags",
			ES: "## Tags",
			EN: "## Tags",
		},
		"edt_doc_tags_intro": {
			PT: "A tag fica **em inglês** e o texto no seu idioma. O motivo é prático: `TODO` e `FIXME` são reconhecidos pelo Go, pelo golangci-lint, pelo gopls e por qualquer IDE; uma tag traduzida perderia tudo isso. Para quem prefere escrever em português ou espanhol, os sinônimos abaixo são varridos e agrupados na tag inglesa.",
			ES: "La tag queda **en inglés** y el texto en su idioma. El motivo es práctico: `TODO` y `FIXME` son reconocidos por Go, por golangci-lint, por gopls y por cualquier IDE; una tag traducida perdería todo eso. Para quien prefiere escribir en portugués o español, los sinónimos de abajo se rastrean y se agrupan en la tag inglesa.",
			EN: "The tag stays **in English** and the text is in your language. The reason is practical: `TODO` and `FIXME` are recognized by Go, by golangci-lint, by gopls and by any IDE; a translated tag would lose all of that. For those who prefer writing in Portuguese or Spanish, the synonyms below are scanned and grouped under the English tag.",
		},
		"edt_doc_tags_header": {
			PT: "| Tag | Quando usar | Sinônimos varridos |\n|:---|:---|:---|",
			ES: "| Tag | Cuándo usar | Sinónimos rastreados |\n|:---|:---|:---|",
			EN: "| Tag | When to use | Scanned synonyms |\n|:---|:---|:---|",
		},
		"edt_tag_todo": {
			PT: "trabalho combinado que ainda falta",
			ES: "trabajo acordado que aún falta",
			EN: "agreed work still missing",
		},
		"edt_tag_fixme": {
			PT: "código errado ou frágil que precisa de correção",
			ES: "código incorrecto o frágil que necesita corrección",
			EN: "wrong or fragile code that needs fixing",
		},
		"edt_tag_note": {
			PT: "explicação de uma decisão que não é óbvia no código",
			ES: "explicación de una decisión que no es obvia en el código",
			EN: "explanation of a decision that is not obvious in the code",
		},
		"edt_tag_warn": {
			PT: "armadilha: mexer aqui quebra algo em outro lugar",
			ES: "trampa: tocar aquí rompe algo en otro lugar",
			EN: "trap: touching this breaks something elsewhere",
		},
		"edt_tag_hack": {
			PT: "solução provisória que só existe por uma limitação externa",
			ES: "solución provisional que solo existe por una limitación externa",
			EN: "stopgap that exists only because of an external limitation",
		},
		"edt_tag_gokit": {
			PT: "ponto de contato com o GoKit (regerar, revalidar, migrar)",
			ES: "punto de contacto con GoKit (regenerar, revalidar, migrar)",
			EN: "touch point with GoKit (regenerate, revalidate, migrate)",
		},
		"edt_doc_gen_title": {
			PT: "## Arquivos gerados não recebem anotação",
			ES: "## Los archivos generados no reciben anotaciones",
			EN: "## Generated files carry no annotations",
		},
		"edt_doc_gen_body": {
			PT: "Nenhum `*.gen.go` contém tag de anotação, e a varredura ignora esses arquivos por glob. São duas travas para o mesmo problema: uma tag num arquivo gerado apareceria na sua lista como se fosse trabalho seu, e desapareceria na próxima geração sem que ninguém tivesse feito nada.",
			ES: "Ningún `*.gen.go` contiene tags de anotación, y el rastreo ignora esos archivos por glob. Son dos trabas para el mismo problema: una tag en un archivo generado aparecería en su lista como si fuera trabajo suyo, y desaparecería en la próxima generación sin que nadie hubiera hecho nada.",
			EN: "No `*.gen.go` contains an annotation tag, and the scan skips those files by glob. Two guards for the same problem: a tag in a generated file would show up in your list as if it were your work, and would vanish on the next generation without anyone having done a thing.",
		},
		"edt_doc_editors_title": {
			PT: "## Por editor",
			ES: "## Por editor",
			EN: "## Per editor",
		},
		"edt_doc_vscode": {
			PT: "**VS Code / Cursor / Windsurf** — o `.vscode/extensions.json` gerado sugere as extensões e o `.vscode/settings.json` já traz as tags, os sinônimos, as cores e o glob de exclusão. As extensões sugeridas são: Go, todo-tree (árvore de anotações), REST Client (executa o `api.gen.http` direto do editor), Markdown All in One com Mermaid (lê a documentação gerada) e Docker.",
			ES: "**VS Code / Cursor / Windsurf** — el `.vscode/extensions.json` generado sugiere las extensiones y el `.vscode/settings.json` ya trae las tags, los sinónimos, los colores y el glob de exclusión. Las extensiones sugeridas son: Go, todo-tree (árbol de anotaciones), REST Client (ejecuta el `api.gen.http` desde el editor), Markdown All in One con Mermaid (lee la documentación generada) y Docker.",
			EN: "**VS Code / Cursor / Windsurf** — the generated `.vscode/extensions.json` suggests the extensions, and `.vscode/settings.json` already carries the tags, the synonyms, the colors and the exclusion glob. The suggested extensions are: Go, todo-tree (annotation tree), REST Client (runs `api.gen.http` from the editor), Markdown All in One with Mermaid (reads the generated documentation) and Docker.",
		},
		"edt_doc_jetbrains": {
			PT: "**GoLand / IntelliJ** — não precisa de plugin: a janela **TODO** já lista as anotações, arquivos `.http` são executados nativamente pelo HTTP Client e `.md` tem visualização embutida. Para varrer os sinônimos em português, acrescente os padrões em *Settings → Editor → TODO*. Para ocultar os gerados, use o escopo *Project Files sem `*.gen.go`* no filtro da janela TODO.",
			ES: "**GoLand / IntelliJ** — no necesita plugin: la ventana **TODO** ya lista las anotaciones, los archivos `.http` se ejecutan nativamente por el HTTP Client y `.md` tiene vista previa integrada. Para rastrear los sinónimos en español, agregue los patrones en *Settings → Editor → TODO*. Para ocultar los generados, use el ámbito *Project Files sin `*.gen.go`* en el filtro de la ventana TODO.",
			EN: "**GoLand / IntelliJ** — no plugin needed: the **TODO** window already lists the annotations, `.http` files run natively through the HTTP Client, and `.md` has a built-in preview. To scan the translated synonyms, add the patterns under *Settings → Editor → TODO*. To hide generated files, use a *Project Files without `*.gen.go`* scope in the TODO window filter.",
		},
		"edt_doc_neovim": {
			PT: "**Neovim / Helix / Emacs** — as anotações são texto, então `grep`, `ripgrep` ou a lista de quickfix já resolvem. No Neovim, `todo-comments.nvim` faz o mesmo papel do todo-tree; aponte os sinônimos na configuração dele e exclua `*.gen.go` do `rg`.",
			ES: "**Neovim / Helix / Emacs** — las anotaciones son texto, así que `grep`, `ripgrep` o la lista de quickfix ya resuelven. En Neovim, `todo-comments.nvim` cumple el mismo papel que todo-tree; indique los sinónimos en su configuración y excluya `*.gen.go` del `rg`.",
			EN: "**Neovim / Helix / Emacs** — the annotations are plain text, so `grep`, `ripgrep` or the quickfix list already do the job. In Neovim, `todo-comments.nvim` plays the same role as todo-tree; point the synonyms at its config and exclude `*.gen.go` from `rg`.",
		},
		"edt_doc_terminal": {
			PT: "**Qualquer terminal** — a varredura sem editor nenhum:",
			ES: "**Cualquier terminal** — el rastreo sin editor alguno:",
			EN: "**Any terminal** — the scan with no editor at all:",
		},
		"edt_doc_editorconfig_title": {
			PT: "## .editorconfig",
			ES: "## .editorconfig",
			EN: "## .editorconfig",
		},
		"edt_doc_editorconfig_body": {
			PT: "O `.editorconfig` na raiz fixa fim de linha, codificação e indentação. Go usa tabulação por decisão do gofmt, e o resto do projeto usa espaço. Praticamente todo editor respeita esse arquivo — alguns nativamente, outros por extensão.",
			ES: "El `.editorconfig` en la raíz fija el fin de línea, la codificación y la indentación. Go usa tabulación por decisión de gofmt, y el resto del proyecto usa espacios. Prácticamente todo editor respeta ese archivo — algunos nativamente, otros por extensión.",
			EN: "The `.editorconfig` at the root pins line endings, encoding and indentation. Go uses tabs because gofmt says so, and the rest of the project uses spaces. Practically every editor honors this file — some natively, others through an extension.",
		},
		"edt_doc_regen": {
			PT: "> [!NOTE]\n> Gerado pelo GoKit no reload. Editar este arquivo é seguro: o GoKit não o sobrescreve depois de criado. As chaves em `.vscode/settings.json` também são preservadas — o gokit só acrescenta as que faltam.",
			ES: "> [!NOTE]\n> Generado por GoKit en el reload. Editar este archivo es seguro: GoKit no lo sobrescribe después de creado. Las claves en `.vscode/settings.json` también se preservan — gokit solo agrega las que faltan.",
			EN: "> [!NOTE]\n> Generated by GoKit during reload. Editing this file is safe: GoKit does not overwrite it once created. The keys in `.vscode/settings.json` are preserved too — gokit only adds the missing ones.",
		},
	})
}
