package migrationgo

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// RefreshCatalog rebuilds dsl.gen.go in GoKit's Core alias area from the tables already known
// by the catalog and from migrate.CreateTable calls written in migration files.
func RefreshCatalog(projectRoot string, migrationsFolder string) error {
	catalogPath := filepath.Join(projectRoot, "internal", "gokit", "core", "migration", "alias", "dsl.gen.go")
	tables := loadCatalog(catalogPath)
	entries, err := os.ReadDir(migrationsFolder)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	known := make(map[string]bool, len(tables))
	for _, name := range tables {
		known[name] = true
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || entry.Name() == "dsl.gen.go" {
			continue
		}
		path := filepath.Join(migrationsFolder, entry.Name())
		file, parseErr := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if parseErr != nil {
			return fmt.Errorf("ler tabelas de %s: %w", entry.Name(), parseErr)
		}
		ast.Inspect(file, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok || len(call.Args) == 0 {
				return true
			}
			selector, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || identName(selector.X) != "migrate" || selector.Sel.Name != "CreateTable" {
				return true
			}
			literal, ok := call.Args[0].(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				return true
			}
			if name, unquoteErr := strconv.Unquote(literal.Value); unquoteErr == nil && name != "" {
				known[name] = true
			}
			return true
		})
	}

	names := make([]string, 0, len(known))
	for name := range known {
		names = append(names, name)
	}
	sort.Strings(names)

	if err := os.MkdirAll(filepath.Dir(catalogPath), 0o755); err != nil {
		return err
	}
	return writeCatalog(catalogPath, names)
}

func writeCatalog(path string, names []string) error {
	var source strings.Builder
	source.WriteString("// Code generated by GoKit. DO NOT EDIT.\npackage alias\n\n")
	source.WriteString("import migrate \"gokit/migration\"\n\n")
	for _, name := range names {
		fmt.Fprintf(&source, "var %s = migrate.Table(%q)\n", exportedIdentifier(name), name)
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

// WriteCoreCatalog writes the project-owned alias catalog in GoKit's
// protected core area. Keys are stable aliases and values are physical names.
func WriteCoreCatalog(projectRoot string, aliases map[string]string) error {
	path := filepath.Join(projectRoot, "internal", "gokit", "core", "migration", "alias", "dsl.gen.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(aliases))
	for alias := range aliases {
		names = append(names, alias)
	}
	sort.Strings(names)
	var source strings.Builder
	source.WriteString("// Code generated by GoKit. DO NOT EDIT.\npackage alias\n\n")
	source.WriteString("import migrate \"gokit/migration\"\n\n")
	source.WriteString("// Catalog mantém o import alias válido em migrations manuais ainda vazias.\n")
	source.WriteString("var Catalog = struct{}{}\n\n")
	// Aliases distintos podem colapsar no mesmo identificador Go
	// (ex.: "milPst" e "mil_pst" viram MilPst), o que geraria um catálogo que
	// não compila. Barramos aqui, com a mensagem apontando os dois culpados.
	claimed := make(map[string]string, len(names))
	for _, alias := range names {
		identifier := exportedIdentifier(alias)
		if previous, taken := claimed[identifier]; taken {
			return fmt.Errorf("os aliases %q e %q geram o mesmo identificador %s no catálogo; escolha apelidos distintos", previous, alias, identifier)
		}
		claimed[identifier] = alias
		fmt.Fprintf(&source, "var %s = migrate.Table(%q) // physical: %s\n", identifier, alias, aliases[alias])
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return err
	}
	legacyPath := filepath.Join(projectRoot, "internal", "gokit", "core", "migration", "table", "dsl.gen.go")
	_ = os.Remove(legacyPath)
	_ = os.Remove(filepath.Dir(legacyPath))
	return nil
}

// PrimeCoreCatalog rebuilds the minimum alias catalog directly from
// CreateTable(...).Alias(...) syntax. It does not depend on the current catalog,
// so Reload can recover automatically if a generated catalog is missing or
// incomplete.
func PrimeCoreCatalog(projectRoot string, paths []string) error {
	aliases := map[string]string{}
	for _, path := range paths {
		if !strings.HasSuffix(strings.ToLower(path), ".go") {
			continue
		}
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if err != nil {
			return fmt.Errorf("ler aliases de %s: %w", filepath.Base(path), err)
		}
		ast.Inspect(file, func(node ast.Node) bool {
			aliasCall, ok := node.(*ast.CallExpr)
			if !ok || len(aliasCall.Args) != 1 {
				return true
			}
			aliasSelector, ok := aliasCall.Fun.(*ast.SelectorExpr)
			if !ok || aliasSelector.Sel.Name != "Alias" {
				return true
			}
			createCall, ok := aliasSelector.X.(*ast.CallExpr)
			if !ok || len(createCall.Args) == 0 {
				return true
			}
			createSelector, ok := createCall.Fun.(*ast.SelectorExpr)
			if !ok || identName(createSelector.X) != "migrate" || createSelector.Sel.Name != "CreateTable" {
				return true
			}
			physical, physicalOK := quotedLiteral(createCall.Args[0])
			alias, aliasOK := quotedLiteral(aliasCall.Args[0])
			if physicalOK && aliasOK && physical != "" && alias != "" {
				aliases[alias] = physical
			}
			return true
		})
	}
	return WriteCoreCatalog(projectRoot, aliases)
}

func quotedLiteral(expression ast.Expr) (string, bool) {
	literal, ok := expression.(*ast.BasicLit)
	if !ok || literal.Kind != token.STRING {
		return "", false
	}
	value, err := strconv.Unquote(literal.Value)
	return value, err == nil
}

// WriteCoreViewCatalog writes the project-owned autocomplete catalog for views.
func WriteCoreViewCatalog(projectRoot string, views map[string]bool) error {
	path := filepath.Join(projectRoot, "internal", "gokit", "core", "migration", "view", "dsl.gen.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(views))
	for name := range views {
		names = append(names, name)
	}
	sort.Strings(names)
	var source strings.Builder
	source.WriteString("// Code generated by GoKit. DO NOT EDIT.\npackage view\n\n")
	source.WriteString("import migrate \"gokit/migration\"\n\n")
	source.WriteString("// Catalog mantém o package válido mesmo quando ainda não há views.\n")
	source.WriteString("var Catalog = struct{}{}\n\n")
	for _, name := range names {
		fmt.Fprintf(&source, "var %s = migrate.RegisteredView(%q)\n", ViewIdentifier(name), name)
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

// ViewIdentifier converts a physical view name to the catalog's Go name.
// The conventional vw prefix is kept as its own word for readable autocomplete.
func ViewIdentifier(value string) string {
	normalized := strings.ToLower(strings.TrimSpace(value))
	if strings.HasPrefix(normalized, "vw") && len(normalized) > 2 && normalized[2] != '_' {
		normalized = "vw_" + normalized[2:]
	}
	return exportedIdentifier(normalized)
}

func exportedIdentifier(value string) string {
	if !strings.ContainsAny(value, "_- .") && value != "" {
		return strings.ToUpper(value[:1]) + value[1:]
	}
	identifier := tableIdentifier(value)
	return strings.ToUpper(identifier[:1]) + identifier[1:]
}

func identName(e ast.Expr) string {
	if i, ok := e.(*ast.Ident); ok {
		return i.Name
	}
	return ""
}
